<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Change_icon-hide show_hide_password</name>
   <tag></tag>
   <elementGuidId>36461812-510b-4a31-9fbd-6b1b0b44f267</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick='showHidePassword();']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.icon-hide.show_hide_password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>11feb804-1688-4f24-93a6-ec4a8abe9712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-hide show_hide_password</value>
      <webElementGuid>25ebfeaf-453b-4da2-ac8b-f057e442f1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showHidePassword();</value>
      <webElementGuid>11be3807-c4b2-4edc-88f8-d26ba325ef27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password_container&quot;)/div[@class=&quot;textbox_div&quot;]/span[@class=&quot;icon-hide show_hide_password&quot;]</value>
      <webElementGuid>117bf9b1-5165-417e-a71d-7b0dcc49fcc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick='showHidePassword();']</value>
      <webElementGuid>2161ca96-dbf8-42fe-8e6d-e01f0152d934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='password_container']/div[2]/span</value>
      <webElementGuid>473d1dd5-b135-4048-991d-822b48f29ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span</value>
      <webElementGuid>e15a267f-ce4a-4aa4-8198-828c431005d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
